// WebsiteBaru/vue-app/src/App.vue
<template>
  <div class="app" style="color:#9afeff; background:#101b22; padding:1rem; border-radius:0.5rem;">
    <h1>Vue Vite App</h1>
    <p>Counter: {{ count }}</p>
    <button @click="count++">Tambah</button>
  </div>
</template>

<script>
export default {
  data() {
    return { count: 0 };
  }
};
</script>

// WebsiteBaru/react-app/src/App.jsx
import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);
  return (
    <div style={{ color: '#c8f7ff', padding: '1rem', background: '#1b1b1b', borderRadius:'0.6rem' }}>
      <h1>React Vite App</h1>
      <p>Counter: {count}</p>
      <button onClick={() => setCount((c) => c + 1)}>Tambah</button>
    </div>
  );
}
